version: '3.8'

services:
  job-matcher:
    build: .
    container_name: job-matcher-service
    ports:
      - "5004:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - LOG_LEVEL=INFO
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s