services:
  app:
    build: .
    container_name: micro-service-job-enricher
    ports:
      - "5002:5000"
    env_file:
      - .env
    volumes:
      - .:/app  # <-- This mounts your current directory (host) to /app (container)
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]