global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aws-microservices'
    static_configs:
      - targets: 
          - 'job-enricher:5001'
          - 'job-extractor:5002'
          - 'job-matcher:5003'
          - 'resume-parser:5004'
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis monitoring disabled for local development to prevent security warnings
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']
  #   metrics_path: /
  #   scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics
    scrape_interval: 30s