name: Deploy to AWS ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      wake_services:
        description: 'Wake up services after deployment'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      scale_count:
        description: 'Number of tasks to run (0 keeps services sleeping)'
        required: false
        default: '0'
        type: string

# Use the cost-optimized workflow
jobs:
  deploy:
    uses: ./.github/workflows/deploy-cost-optimized.yml
    with:
      wake_services: ${{ inputs.wake_services }}
      scale_count: ${{ inputs.scale_count }}
    secrets: inherit